### ISSUE TITLE
Error format with Japanese Katakana characters

### ISSUE THREAD

**Issue by TadaoYamaoka** [qjebbs/vscode-markdown-extended#53] opened 2019-07-02 14:12 UTC
As with issue # 51, it's error format with Japanese Katakana characters.

Now it is like this:
![image](https://user-images.githubusercontent.com/7104722/60519577-c9b25c80-9d1e-11e9-82e5-4567bfdf9819.png)

Refer to the following URL for Katakana.
https://ja.wikipedia.org/wiki/%E7%89%87%E4%BB%AE%E5%90%8D

**Comment by qjebbs** [comment] 2019-07-03 06:54
This commit <https://github.com/qjebbs/vscode-markdown-extended/commit/15dd49f2ee3b647ac588b3ab11ca93f71d3a5f8c> should solve your issue, and potentially more...

https://github.com/qjebbs/vscode-markdown-extended/blob/15dd49f2ee3b647ac588b3ab11ca93f71d3a5f8c/src/services/table/monospace.ts#L3-L20

Closing...

**Closed by qjebbs** 2019-07-03 06:54 UTC

**Comment by TadaoYamaoka** [comment] 2019-07-03 08:06
Your solution is not include U+30FC.
U+30FC(Katakana-Hiragana Prolonged Sound Mark) is very important in Japanese.
U+30FB etc. may also be used.
So, I suggest as below.
"\u30A0-\u30FF" instead of "\\p{Script=Katakana}"
"\u3041-\u309F" instead of "\\p{Script=Hiragana}"

**Comment by qjebbs** [comment] 2019-07-03 09:11
```js
    "\\p{Script=Katakana}",
    // Japanese Punctuation
    "\u3099-\u309A",     //Inherited # Mn   [2] COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK..COMBINING KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
    "\u309B -\u309C",    //Common # Sk   [2] KATAKANA-HIRAGANA VOICED SOUND MARK..KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
    "\u30A0",            //Common # Pd       KATAKANA-HIRAGANA DOUBLE HYPHEN
    "\u30FB",            //Common # Po       KATAKANA MIDDLE DOT
    "\u30FC",            //Common # Lm       KATAKANA-HIRAGANA PROLONGED SOUND MARK
```

Is this enough? I think your suggestion is missing:

```
1B000         ; Katakana # Lo       KATAKANA LETTER ARCHAIC E
1B001..1B11E  ; Hiragana # Lo [286] HIRAGANA LETTER ARCHAIC YE..HENTAIGANA LETTER N-MU-MO-2
1F200         ; Hiragana # So       SQUARE HIRAGANA HOKA
```

and future `Katakana ` and `Hiragana ` expansions.

----

PS: I found previous code a bug, caused by JS calculating `\u30FB` as length of 1, while `\u{1B001} (𛀁)` as length of 2.

now it gives the right result

![image](https://user-images.githubusercontent.com/16953333/60579335-6de6e280-9db5-11e9-8dc8-b3381ae1f7b8.png)

**Comment by TadaoYamaoka** [comment] 2019-07-03 09:28
Thanks, it works well.
